title: Marguerites update Website

author: Marguerite Price
email: masm1781@gmail.com

description: > #This site will be used to post updates on my life and learning coding.

# social links
twitter_username: xsassykittyx
github_username:  masm1781

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
